version: '3.1'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=form3
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_USER=felix
    ports:
      - "5432:5432"

#version: '2'
#services:
  #db:
    #image: postgres:9.5
    #ports:
    #- "5432"